name: Dispatch event!
description: Create workflow_dispatch or repository_dispatch events
branding:
  icon: wifi
  color: purple
runs:
  using: node12
  main: dist-ncc/index.js
inputs:
  repo:
    description: Repository
    required: false
  token:
    description: Personal access token
    required: true
  type:
    description: Workflow or repository dispatch
    default: workflow
  ident:
    description: Event identifier
    required: true
  payload:
    description: Payload for the dispatched event
    required: false
